### ISSUE TITLE
How to set custom keys

### ISSUE THREAD

**Issue by FlorentAnders** [kudlaj/fmplaylist#1]
Hello!

Where can I set the API keys for Jamendo, Soundcloud and FMA?

Thanks

**Comment by kudlaj** [comment]
Hi,
you need a file called private.js in the js folder
with this code:
var PrivateKeys = (function () {
  var privateKeys = {
            JAMENDO_KEY : "xxxxxx",
            SOUNDCLOUD_KEY : "xxxx",
            FMA_KEY : "xxxx",
            LASTFM_KEY : "xxxxx",
            ECHONEST_KEY : "xxxxx"
            };

```
return privateKeys;
```

}());

Best,
Jürgen

On Thu, Sep 18, 2014 at 8:23 PM, Florent1510 notifications@github.com
wrote:

> Hello!
> 
> Where can I set the API keys for Jamendo, Soundcloud and FMA?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kudlaj/fmplaylist/issues/1.

## 

Jürgen Kudla
